version: '3.5'

services:
  admin:
    container_name: mw-mp-admin
    build: .
    image: mw-mp-admin
    networks:
      - mwnet
    restart: unless-stopped

networks:
  mwnet:
    name: mw-mp_mwnet
